easings = {
     0 : "easeLinear",
     1 : "easeInSine",
     2 : "easeOutSine",
     3 : "easeInOutSine",
     4 : "easeInCubic",
     5 : "easeOutCubic",
     6 : "easeInOutCubic",
     7 : "easeInQuint",
     8 : "easeOutQuint",
     9 : "easeInOutQuint",
    10 : "easeInCirc" ,
    11 : "easeOutCirc" ,
    12 : "easeInOutCirc" ,
    13 : "easeInElastic" ,
    14 : "easeOutElastic" ,
    15 : "easeInOutElastic" ,
    16 : "easeInQuad" ,
    17 : "easeOutQuad" ,
    18 : "easeInOutQuad" ,
    19 : "easeInQuart" ,
    20 : "easeOutQuart" ,
    21 : "easeInOutQuart" ,
    22 : "easeInExpo" ,
    23 : "easeOutExpo" ,
    24 : "easeInOutExpo" ,
    25 : "easeInBack" ,
    26 : "easeOutBack" ,
    27 : "easeInOutBack" ,
    28 : "easeInBounce" ,
    29 : "easeOutBounce" ,
    30 : "easeInOutBounce"
}

zones = {
    0: "Back Lasers",
    1: "Ring Light",
    2: "Left Lasers ",
    3: "Right Lasers ",
    4: "Center Light",
    5: "Color bis",
    6: "Interscope left ",
    7: "Interscope right",
}